/* ====================================================================================
CMPS3162 - Test #2: PostgreSQL Job Queue (Music Processing) 
Jennessa Sierra - 2021153908@ub.edu.bz
PostgreSQL 18.3
May 14, 2026
==================================================================================== */

/* ====================================================================================
SETUP - Database Initialization
This preliminary phase removes all existing database contents, enabling this script to be
re-executed and modified iteratively using the \i music_jobs.sql command in psql.
==================================================================================== */

DROP TABLE IF EXISTS music_jobs;

/* ====================================================================================
STEP 1 - id, payload, created_at
===================================================================================== */
CREATE TABLE music_jobs (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

----- Q & A -----

/* 1. Why UUID over SERIAL for the primary key?
The UUID data type provides a globally unique identifier that is not tied to a specific sequence
or server instance, making it ideal for distributed systems and ensuring uniqueness across different
environments. In contrast, SERIAL is an auto-incrementing integer that can lead to conflicts in
distributed setups and does not guarantee uniqueness across multiple databases. */

/* 2. Why uuidv7() specifically over uuidv4()? 
The uuidv7() function generates time-ordered UUIDs, which can improve performance when used as
primary keys in databases. Time-ordered UUIDs can reduce fragmentation and improve indexing
efficiency compared to random UUIDs generated by uuidv4(), which do not have any inherent order.
This makes uuidv7() a better choice for scenarios where the order of record creation is important,
such as in job queues. */

/* 3. Why JSONB over JSON?
The JSONB data type stores JSON data in a binary format, which allows for faster access and
querying compared to the plain JSON data type. JSONB supports indexing, which can significantly
improve performance when querying specific fields within the JSON data. Additionally, JSONB
automatically removes duplicate keys and does not preserve the order of object keys, which can lead
to more efficient storage. In contrast, JSON stores data as text and does not support indexing,
resulting in slower query performance when accessing specific fields. */

/* 4. Why TIMESTAMPTZ over TIMESTAMP?
The TIMESTAMPTZ data type includes time zone information, allowing for accurate representation of
timestamps across different time zones. This is particularly important in distributed systems or
applications that may be used globally, as it ensures that timestamps are consistent and can be
correctly interpreted regardless of the user's location. In contrast, the TIMESTAMP data type does
not include time zone information, which can lead to confusion and errors when dealing with timestamps
from different time zones. */

----- SAMPLE DATA -----

INSERT INTO
    music_jobs (payload)
VALUES (
    '{
        "filename": "wadani_le.mp3",
        "storage_path": "/music/uploads/wadani_le.mp3",
        "file_size": 5242880,
        "mime_type": "audio/mpeg",
        "title": "Wadani Le",
        "album": "Undeniable",
        "artist": "Supa G",
        "genre": "Punta Rock",
        "year": 2016,
        "duration": 167
    }'::JSONB
);

SELECT pg_sleep(1); -- utilized to create a time gap between entries for testing purposes

INSERT INTO
    music_jobs (payload)
VALUES (
    '{
        "filename": "good_mawnin_belize.mp3",
        "storage_path": "/music/uploads/good_mawnin_belize.mp3",
        "file_size": 7340032,
        "mime_type": "audio/wav",
        "title": "Good Mawnin Belize",
        "album": "This is Belize",
        "artist": "Mr. Peters",
        "genre": "Tropical",
        "year": 2007,
        "duration": 195
    }'::JSONB
);

SELECT pg_sleep(1);

-- contains extra field "bitrate"
INSERT INTO
    music_jobs (payload)
VALUES (
    '{
        "filename": "born_deh.mp3",
        "storage_path": "/music/uploads/born_deh.mp3",
        "file_size": 10485760,
        "mime_type": "audio/mpeg",
        "title": "Born Deh",
        "album": "The Legend",
        "artist": "Lord Rhaburn",
        "genre": "Calypso",
        "year": 2009,
        "duration": 350,
        "bitrate": 320
    }'::JSONB
);

----- VERIFICATION QUERIES -----

/* 1. Show all jobs ordered by creation time
SELECT payload->>'title' AS title, created_at FROM music_jobs ORDER BY created_at;

       title        |          created_at           
--------------------+-------------------------------
 Wadani Le          | 2026-05-14 00:01:15.633682-06
 Good Mawnin Belize | 2026-05-14 00:01:16.637025-06
 Born Deh           | 2026-05-14 00:01:17.650626-06
(3 rows) */

/* 2. Extract just the filename and mime_type from each job 
SELECT payload->>'filename' AS filename, payload->>'mime_type' AS mime_type FROM music_jobs;

        filename        | mime_type  
------------------------+------------
 wadani_le.mp3          | audio/mpeg
 good_mawnin_belize.mp3 | audio/wav
 born_deh.mp3           | audio/mpeg
(3 rows) */

/* 3. Find only MP3 uploads
SELECT payload->>'filename' AS filename, payload->>'mime_type' AS mime_type
FROM music_jobs WHERE payload->>'mime_type' = 'audio/mpeg';

   filename    | mime_type  
---------------+------------
 wadani_le.mp3 | audio/mpeg
 born_deh.mp3  | audio/mpeg
(2 rows) */

/* 4. Find the job that has the extra field
SELECT payload->>'id' AS id, payload->>'filename' AS filename, payload->>'bitrate' AS bitrate
FROM music_jobs WHERE payload ? 'bitrate';

                  id                  |   filename   | bitrate 
--------------------------------------+--------------+---------
 019e2517-17d8-7a06-bb49-d8d0edcdc46c | born_deh.mp3 | 320
(1 row) */

/* ====================================================================================
STEP 2 - public_id
==================================================================================== */

ALTER TABLE music_jobs
    ADD COLUMN public_id UUID UNIQUE NOT NULL DEFAULT uuidv4();

----- Q & A -----

/* 1. Why does this column use uuidv4() and not uuidv7()?
The public_id column uses uuidv4() because it is intended to be a unique identifier that is not
necessarily time-ordered. Since public_id may be exposed to external systems or users, using uuidv4()
ensures that the IDs are random and do not reveal any information about the order of record creation.
In contrast, uuidv7() generates time-ordered UUIDs, which may not be suitable for public-facing
identifiers. This is because they can potentially be analyzed by malicious actors to infer
information about the system's activity patterns, which can be exploited by a competitor or used to
time a DDoS attack. */

/* 2. What does uuid_extract_timestamp() reveal about uuidv7?
The uuid_extract_timestamp() function can be used to extract the timestamp component from a uuidv7()
UUID. This reveals the exact time when the UUID was generated, which can provide insights into the
order of record creation and the timing of events in the system. This information can be useful for
debugging, auditing, or analyzing system performance, but it can also pose a security risk if exposed
publicly, as discussed in Question 1. */

/* 3. Why does the UNIQUE constraint make CREATE INDEX unnecessary? 
In PostgreSQL, the UNIQUE constraint on the public_id column automatically creates a unique index on
that column. This means that the database will enforce uniqueness and optimize queries based on the
public_id without the need for an additional CREATE INDEX statement. The UNIQUE constraint ensures
that no two records can have the same public_id, while also providing efficient lookups through the
underlying index. Therefore, adding a separate CREATE INDEX would be redundant and unnecessary. */

/* 4. What is the two-ID pattern and why does it matter?
The two-ID pattern refers to the practice of using two different types of identifiers in a database:
a primary key (id) that is used internally for database operations, and a public identifier
(public_id) that is exposed to external systems or users. This pattern matters because it allows
for better security and flexibility. The primary key can be optimized for database performance and
internal use, while the public identifier can be designed to be more user-friendly and secure for
external use. By separating these two identifiers, developers can ensure that sensitive information
about the database structure is not exposed to the public, while still providing a way to reference
records in a secure and efficient manner. */

----- VERIFICATION QUERIES -----

/* 1. Show id vs public_id side by side - what do you notice?
SELECT id, public_id FROM music_jobs;

                  id                  |              public_id               
--------------------------------------+--------------------------------------
 019e2536-f793-72b2-9894-c93f65472184 | b31dedca-4c25-471d-8b13-128d77a24681
 019e2536-fb7e-77cd-a568-594f75c73e38 | 7f3103a3-b2fe-438a-83ca-dfdbcf8c0674
 019e2536-ff76-729e-9315-01539e12c6cf | a60e6cb3-ed14-4a79-a4c1-84be9e6e71ba
(3 rows)

Upon inspection, you immediately notice that the id values all begin with the same prefix "019e2536",
which corresponds to the timestamp component of uuidv7() UUIDs. In contrast, the public_id values
are completely random and do not share any common prefix, which is typical of uuidv4() UUIDs. */

/* 2. Run uuid_extract_timestamp() on both columns - what does this prove?
SELECT uuid_extract_timestamp(id) AS id_timestamp, uuid_extract_timestamp(public_id) AS public_id_timestamp
FROM music_jobs;

        id_timestamp        | public_id_timestamp 
----------------------------+---------------------
 2026-05-14 00:40:19.859-06 | 
 2026-05-14 00:40:20.862-06 | 
 2026-05-14 00:40:21.878-06 | 
(3 rows)

These results prove that the uuidv7() UUIDs in the id column contain timestamp information, while
the uuidv4() UUIDs in the public_id column do not. */

/* 3. Show what the Go server would return to the client after insert

HTTP/2 202
date: Fri, 14 May 2026 00:01:15 GMT
content-type: application/json
content-length: 56
{
"job_id": "b31dedca-4c25-471d-8b13-128d77a24681"
}

Upon insert, the Go server would return the above JSON response that includes the public_id (job_id).
The client can then use this job_id to poll for the job status. One thing to note is that the HTTP
202 status code indicates that the request has been accepted for processing, but not yet completed. */

/* 4. Show what the Go server would do when the client polls

HTTP/2 200 
date: Fri, 14 May 2026 00:02:31 GMT
content-type: application/json
content-length: 50
{
    "status": "processing",
    "progress": 75
}

Upon polling, the Go server would return the above JSON response that includes the job status and
progress. The HTTP 200 status code indicates that the job is OK and started processing. Please note,
the status and progress columns are created and developed in the subsequent steps. */

/* ====================================================================================
STEP 3 - status, progress
==================================================================================== */

ALTER TABLE music_jobs
    ADD COLUMN status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing', 'done', 'failed')),
    ADD COLUMN progress INTEGER NOT NULL DEFAULT 0
        CHECK (progress BETWEEN 0 AND 100);

----- Q & A -----

/* 1. Why are status and progress real columns, not inside payload JSONB?
Storing status and progress as real columns allows for more efficient querying and indexing compared
to storing them inside the payload JSONB. Real columns can be indexed, which improves performance
when filtering or sorting based on these fields. In contrast, querying JSONB fields requires
additional overhead to parse the JSON data, which can lead to slower performance. Additionally,
having status and progress as separate columns allows for easier updates and maintenance, as they
can be modified directly without the need to manipulate the JSON structure. */

/* 2. What happens if a buggy worker writes status = 'complet'?
If a buggy worker writes status = 'complet', the CHECK constraint will prevent the update from
succeeding, as 'complet' is not one of the allowed values. Therefore, the update will be rejected
and an error will be returned. */

/* 3. Why does the CHECK constraint matter more than application validation? 
The CHECK constraint at the database level provides an additional layer of data integrity that is
enforced regardless of the application logic. This means that even if there is a bug in the application
that allows invalid data to be generated, the database will still reject it, ensuring that the data
remains consistent and valid. Relying solely on application validation can lead to situations where
invalid data is inserted into the database due to bugs or oversights in the application code, which
can cause issues down the line when querying or processing that data. */

/* 4. Draw the state machine for a job lifecycle
    
        +-------+         +----------+      worker claims job     +------------+
        | START | ------> | PENDING  | -----------------------> | PROCESSING |
        +-------+         +----------+                           +------------+
                                                                 |            |
                                             all stages succeed  |            | stage fails
                                                                 v            v
                                                             +------+    +--------+
                                                             | DONE |    | FAILED |
                                                             +------+    +--------+
                                                                 |            |
                                                                 +-----+------+
                                                                       |
                                                                       v
                                                                    +-----+
                                                                    | END |
                                                                    +-----+

Terminal states:
   DONE
   FAILED

A job starts in PENDING. Once a worker claims it, the job moves to PROCESSING. From PROCESSING,
it can move to DONE if all processing stages succeed, or FAILED if any stage fails. START and END
are used as placeholders to represent a UML state machine diagram's initial and final states
symbols, respectively. */

----- SAMPLE DATA -----

-- claim the oldest pending job and update its status to processing with 25% progress
UPDATE music_jobs
SET status = 'processing', progress = 25
WHERE id = (SELECT id FROM music_jobs ORDER BY created_at LIMIT 1);

-- update the same job to 50% progress
UPDATE music_jobs
SET progress = 50
WHERE id = (SELECT id FROM music_jobs ORDER BY created_at LIMIT 1);

-- update the same job's status to done with 100% progress
UPDATE music_jobs
SET status = 'done', progress = 100
WHERE id = (SELECT id FROM music_jobs ORDER BY created_at LIMIT 1);

-- attempt an invalid update to the same job's status and progress
UPDATE music_jobs
SET status = 'invalid', progress = 110
WHERE id = (SELECT id FROM music_jobs ORDER BY created_at LIMIT 1);

/* ERROR: new row for relation "music_jobs" violates check constraint "music_jobs_status_check",
   ERROR: new row for relation "music_jobs" violates check constraint "music_jobs_progress_check" */

----- VERIFICATION QUERIES -----

-- update another job's status to processing so that it can be used for the next steps
UPDATE music_jobs
SET status = 'processing', progress = 25
WHERE id = (SELECT id FROM music_jobs WHERE status = 'pending' ORDER BY created_at LIMIT 1);

/* 1. What does the client see when polling a processing job?
SELECT status, progress FROM music_jobs WHERE public_id = '7f3103a3-b2fe-438a-83ca-dfdbcf8c0674';

   status   | progress 
------------+----------
 processing |       25
(1 row)

The client would see a JSON response similar to the following when polling a processing job:

HTTP/2 200
date: Fri, 14 May 2026 00:03:47 GMT
content-length: 50
{
    "status": "processing",
    "progress": 25
} */

/* 2. What query does the worker run to find its next job?
SELECT id FROM music_jobs WHERE status = 'pending' ORDER BY created_at LIMIT 1;

                  id                  
--------------------------------------
 019e2887-bd83-7862-9312-4116f23aa216
(1 row) */

/* 3. Show all jobs with their current state 
SELECT id, payload->>'title' AS title, status, progress, created_at FROM music_jobs ORDER BY created_at;

                  id                  |       title        |   status   | progress |          created_at           
--------------------------------------+--------------------+------------+----------+-------------------------------
 019e2887-b5a1-78bc-958b-8fdd00a690e1 | Wadani Le          | done       |      100 | 2026-05-14 16:07:23.041211-06
 019e2887-b98d-78f8-a533-e8537001f6bc | Good Mawnin Belize | processing |       25 | 2026-05-14 16:07:24.04539-06
 019e2887-bd83-7862-9312-4116f23aa216 | Born Deh           | pending    |        0 | 2026-05-14 16:07:25.059356-06
(3 rows) */

/* ====================================================================================
STEP 4 - result, error_msg
==================================================================================== */

ALTER TABLE music_jobs
    ADD COLUMN result JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN error_msg TEXT;

----- Q & A -----
/* 1. Why does the result default to '{}' and not NULL?
Defaulting the result column to '{}' ensures that it always contains a valid JSONB object, even if no
result data is available. This allows for consistent handling of the result field in application code,
as it can always expect a JSON object rather than having to check for NULL values. Additionally, using
an empty JSON object as the default value can simplify queries and updates that interact with the result
column, as it eliminates the need for special handling of NULL cases. In contrast, if the default were NULL,
application code would need to include additional logic to handle potential NULL values, which can lead to
more complex and error-prone code. */

/* 2. Why is error_msg TEXT and not inside the result JSONB? 
error_msg is stored as a separate column because it represents a distinct piece of information from the
result. While the result JSONB contains the output of the job, error_msg specifically captures any
errors that occurred during the job execution. This separation allows for clearer data organization and
easier querying of error conditions without having to parse through the result JSONB field. */

/* 3. What does the || operator do to a JSONB object?
The merge (||) operator in PostgreSQL is used to concatenate two JSONB objects. When applied, it merges the
key-value pairs of both JSONB objects. If there are duplicate keys, the values from the right-hand operand
will overwrite those from the left-hand operand. This operator allows for easy combination of JSONB data,
making it useful for updating or augmenting existing JSONB fields with new information. */

/* 4. Why does each stage read from the original file, not the previous stage's output?
Each stage reads from the original file rather than the previous stage's output to ensure data integrity
and avoid compounding errors. If each stage were to read from the previous stage's output, any errors or
issues that arise in one stage could be propagated and amplified in subsequent stages, making it more
difficult to identify and troubleshoot problems. Additionally, by always reading from the original file,
each stage can operate independently, allowing for better error isolation, easier debugging, and the
ability to be processed in parallel. */

----- SAMPLE DATA -----

-- STAGE 1: Normalize
UPDATE music_jobs
SET status = 'processing', progress = 25,
result = result || jsonb_build_object(
    'normalized_path', '/music/uploads/processsed/normalized/' || md5(payload->>'title') || '_normalized.wav'
)
WHERE id = (SELECT id FROM music_jobs ORDER BY created_at LIMIT 1);

/* SELECT payload->>'title' AS title, status, progress, result
   FROM music_jobs WHERE id = (SELECT id FROM music_jobs ORDER BY created_at LIMIT 1);

   title   |   status   | progress |                                              result                                              
-----------+------------+----------+--------------------------------------------------------------------------------------------------
 Wadani Le | processing |       25 | {"normalized_path": "/music/uploads/processsed/normalized/102f09505b35f531f470b836d5612a45_normalized.wav"}
(1 row) */

-- STAGE 2: Trim Silence
UPDATE music_jobs
SET progress = 50,
result = result || jsonb_build_object(
    'trimmed_path', '/music/uploads/processsed/trimmed/' || md5(payload->>'title') || '_trimmed.wav'
)
WHERE id = (SELECT id FROM music_jobs ORDER BY created_at LIMIT 1);

/* SELECT payload->>'title' AS title, status, progress, result
   FROM music_jobs WHERE id = (SELECT id FROM music_jobs ORDER BY created_at LIMIT 1);

   title   |   status   | progress |                                                                                                    result                                                                                                     
-----------+------------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Wadani Le | processing |       50 | {"trimmed_path": "/music/uploads/processsed/trimmed/102f09505b35f531f470b836d5612a45_trimmed.wav", "normalized_path": "/music/uploads/processsed/normalized/102f09505b35f531f470b836d5612a45_normalized.wav"}
(1 row) */

-- STAGE 3: Convert Format
UPDATE music_jobs
SET progress = 75,
result = result || jsonb_build_object(
    'converted_path', '/music/uploads/processsed/converted/' || md5(payload->>'title') || '_converted.mp3'
)
WHERE id = (SELECT id FROM music_jobs ORDER BY created_at LIMIT 1);

/* SELECT payload->>'title' AS title, status, progress, result
   FROM music_jobs WHERE id = (SELECT id FROM music_jobs ORDER BY created_at LIMIT 1);

   title   |   status   | progress |                                                                                                                                                        result                                                                                                                                                         
-----------+------------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Wadani Le | processing |       75 | {"trimmed_path": "/music/uploads/processsed/trimmed/102f09505b35f531f470b836d5612a45_trimmed.wav", "converted_path": "/music/uploads/processsed/converted/102f09505b35f531f470b836d5612a45_converted.mp3", "normalized_path": "/music/uploads/processsed/normalized/102f09505b35f531f470b836d5612a45_normalized.wav"}
(1 row) */

-- STAGE 4: Waveform Generation
UPDATE music_jobs
SET status = 'done', progress = 100,
result = result || jsonb_build_object(
    'waveform_path', '/music/uploads/processsed/waveforms/' || md5(payload->>'title') || '_waveform.json'
)
WHERE id = (SELECT id FROM music_jobs ORDER BY created_at LIMIT 1);

/* SELECT payload->>'title' AS title, status, progress, result
   FROM music_jobs WHERE id = (SELECT id FROM music_jobs ORDER BY created_at LIMIT 1);

   title   | status | progress |                                                                                                                                                                                                            result                                                                                                                                                                                                            
-----------+--------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Wadani Le | done   |      100 | {"trimmed_path": "/music/uploads/processsed/trimmed/102f09505b35f531f470b836d5612a45_trimmed.wav", "waveform_path": "/music/uploads/processsed/waveforms/102f09505b35f531f470b836d5612a45_waveform.json", "converted_path": "/music/uploads/processsed/converted/102f09505b35f531f470b836d5612a45_converted.mp3", "normalized_path": "/music/uploads/processsed/normalized/102f09505b35f531f470b836d5612a45_normalized.wav"}
(1 row) */

-- Simulate a failure in the next job by updating its status to failed and adding an error message
UPDATE music_jobs
SET status = 'failed', progress = 50, error_msg = 'Failed to trim silence due to invalid audio format'
WHERE id = (SELECT id FROM music_jobs ORDER BY created_at OFFSET 1 LIMIT 1);

/* SELECT payload->>'title' AS title, status, progress, error_msg
   FROM music_jobs WHERE id = (SELECT id FROM music_jobs ORDER BY created_at OFFSET 1 LIMIT 1);

       title        | status | progress |                         error_msg                         
--------------------+--------+----------+-----------------------------------------------------
 Good Mawnin Belize | failed |       50 | Failed to trim silence due to invalid audio format
(1 row) */

----- VERIFICATION QUERIES -----

/* 1. What does the client see when polling a completed job?
The client would see a JSON response similar to the following when polling a completed job:

HTTP/2 200 
date: Thu, 14 May 2026 00:05:47 GMT
content-type: application/json
content-length: 600
{
    "status": "done",
    "progress": 100,
    "result": {
        "trimmed_path": "/music/uploads/processsed/trimmed/102f09505b35f531f470b836d5612a45_trimmed.wav",
        "waveform_path": "/music/uploads/processsed/waveforms/102f09505b35f531f470b836d5612a45_waveform.json",
        "converted_path": "/music/uploads/processsed/converted/102f09505b35f531f470b836d5612a45_converted.mp3",
        "normalized_path": "/music/uploads/processsed/normalized/102f09505b35f531f470b836d5612a45_normalized.wav"
    }
} */

/* 2. What does the client see mid-processing (partial result)? 
HTTP/2 200
date: Thu, 14 May 2026 00:05:31 GMT
content-type: application/json
content-length: 362
{
    "status": "processing",
    "progress": 50,
    "result": {
        "trimmed_path": "/music/uploads/processsed/trimmed/102f09505b35f531f470b836d5612a45_trimmed.wav",
        "normalized_path": "/music/uploads/processsed/normalized/102f09505b35f531f470b836d5612a45_normalized.wav",
    }
}

This would be assuming that each stage is stored as a separate component within the result object that
the client can access while the job is in progress. */

/* 3. How do you find all failed jobs? 
SELECT id, payload->>'title' AS title, status, progress FROM music_jobs WHERE status = 'failed';

                  id                  |       title        | status | progress 
--------------------------------------+--------------------+--------+----------
 019e2935-095c-7ca2-ae54-4cc6ad8655b0 | Good Mawnin Belize | failed |       50
(1 row) */

/* 4. Show the full result object for a completed job 
SELECT public_id, payload->>'title' AS title, status, progress, result FROM music_jobs
WHERE status = 'done' LIMIT 1;

              public_id               |   title   | status | progress |                                                                                                                                                                                                            result                                                                                                                                                                                                   
--------------------------------------+-----------+--------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 a14ceb19-6096-4904-a513-bb97e67e20cb | Wadani Le | done   |      100 | {"trimmed_path": "/music/uploads/processsed/trimmed/102f09505b35f531f470b836d5612a45_trimmed.wav", "waveform_path": "/music/uploads/processsed/waveforms/102f09505b35f531f470b836d5612a45_waveform.json", "converted_path": "/music/uploads/processsed/converted/102f09505b35f531f470b836d5612a45_converted.mp3", "normalized_path": "/music/uploads/processsed/normalized/102f09505b35f531f470b836d5612a45_normalized.wav"}
(1 row) */

/* ====================================================================================
STEP 5 - updated_at
==================================================================================== */

ALTER TABLE music_jobs
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

----- Q & A -----
/* 1. Why is created_at not enough?
created_at only tells us when the job was first created, but doesn't tell us when it was last updated.
By adding updated_at, we can track the last time the job's status or progress was modified. This can
be useful for tracking how long a job has been in progress or if it has stalled. */

/* 2. What goes wrong if application code maintains updated_at?
If application code is responsible for maintaining updated_at, there is a risk of human error or bugs
that could lead to incorrect timestamps being recorded. For example, if a developer forgets to update
the updated_at field after changing the job's status or progress, it could lead to confusion and
inaccurate tracking of job updates. */

/* 3. Write a query that would power an SSE health check endpoint
SELECT public_id, status, progress, result, error_msg, updated_at
FROM music_jobs WHERE public_id = $1 AND updated_at > $2;

This query would allow the SSE health check endpoint to retrieve the latest status and progress of a
specific job based on its public_id, while also ensuring that the information is up-to-date by
filtering for records that have been updated after a certain timestamp ($2). */

----- SAMPLE DATA -----

-- Update a job's progress without setting updated_at manually
/* BEFORE UPDATE:
SELECT id, payload->>'title' AS title, status, progress, updated_at
FROM music_jobs ORDER BY created_at OFFSET 2 LIMIT 1;

                  id                  |  title   | status  | progress |          updated_at           
--------------------------------------+----------+---------+----------+-------------------------------
 019e296e-7a2e-77bb-ac08-1a4b044dace9 | Born Deh | pending |        0 | 2026-05-14 20:19:26.674747-06
(1 row) */

UPDATE music_jobs
SET status = 'processing', progress = 25,
result = result || jsonb_build_object(
    'normalized_path', '/music/uploads/processsed/normalized/' || md5(payload->>'title') || '_normalized.wav'
)
WHERE id = (SELECT id FROM music_jobs ORDER BY created_at OFFSET 2 LIMIT 1); -- updating the third job for testing

/* AFTER UPDATE:
SELECT id, payload->>'title' AS title, status, progress, updated_at
FROM music_jobs ORDER BY created_at OFFSET 2 LIMIT 1;

                  id                  |  title   |   status   | progress |          updated_at           
--------------------------------------+----------+------------+----------+-------------------------------
 019e296e-7a2e-77bb-ac08-1a4b044dace9 | Born Deh | processing |       25 | 2026-05-14 20:19:26.674747-06
(1 row)

Notice the updated_at timestamp has remained unchanged after the update and retains the stale data. */

-- Update the same job with the correct updated_at value using now()
UPDATE music_jobs
SET progress = 50, updated_at = now(),
result = result || jsonb_build_object(
    'trimmed_path', '/music/uploads/processsed/trimmed/' || md5(payload->>'title') || '_trimmed.wav'
)
WHERE id = (SELECT id FROM music_jobs ORDER BY created_at OFFSET 2 LIMIT 1);

/* AFTER UPDATE WITH CORRECT updated_at:
SELECT id, payload->>'title' AS title, status, progress, updated_at
FROM music_jobs ORDER BY created_at OFFSET 2 LIMIT 1;

                  id                  |  title   |   status   | progress |          updated_at          
--------------------------------------+----------+------------+----------+------------------------------
 019e296e-7a2e-77bb-ac08-1a4b044dace9 | Born Deh | processing |       50 | 2026-05-14 20:26:24.92658-06
(1 row)

Notice the updated_at timestamp has been correctly updated to reflect the latest change this time. */

-- Explain why this is fragile
/* This approach is fragile because it relies on the application code to manually update the updated_at
field. If the application code forgets to update this field or updates it incorrectly, it can lead to
inaccurate tracking of job updates. This can result in confusion and inaccurate reporting of job statuses. */

----- VERIFICATION QUERIES -----

/* 1. Find jobs that changed in the last 60 seconds 
SELECT id, payload->>'title' AS title, status, progress, updated_at
FROM music_jobs WHERE updated_at > now() - INTERVAL '60 seconds' ORDER BY updated_at DESC

 id | title | status | progress | updated_at 
----+-------+--------+----------+------------
(0 rows)

Note that no jobs have changed in the last 60 seconds. */

/* 2. Find jobs stuck in processing for more than 5 minutes
SELECT id, payload->>'title' AS title, status, progress, created_at, updated_at
FROM music_jobs WHERE status = 'processing' AND updated_at < now() - INTERVAL '5 minutes';

                  id                  |  title   |   status   | progress |          created_at          |          updated_at          
--------------------------------------+----------+------------+----------+------------------------------+------------------------------
 019e296e-7a2e-77bb-ac08-1a4b044dace9 | Born Deh | processing |       50 | 2026-05-14 20:19:26.63836-06 | 2026-05-14 20:26:24.92658-06
(1 row) */

/* 3. How long did each completed job take?
SELECT id, payload->>'title' AS title, status, progress, updated_at - created_at AS job_duration
FROM music_jobs WHERE status = 'done';

                  id                  |   title   | status | progress |  job_duration  
--------------------------------------+-----------+--------+----------+----------------
 019e296e-724c-7a3c-9ebc-a01e6fe775a1 | Wadani Le | done   |      100 | 00:00:02.05437
(1 row) */
