/* ====================================================================================
CMPS3162 - Test #2: PostgreSQL Job Queue (Music Processing) 
Jennessa Sierra - 2021153908@ub.edu.bz
PostgreSQL 18.3
May 14, 2026
==================================================================================== */

/* ====================================================================================
SETUP - Database Initialization
This preliminary phase removes all existing database contents, enabling this script to be
re-executed and modified iteratively using the \i music_jobs.sql command in psql.
==================================================================================== */

DROP TABLE IF EXISTS music_jobs;

/* ====================================================================================
STEP 1 - id, payload, created_at
===================================================================================== */
CREATE TABLE music_jobs (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

----- Q & A -----
/* 1. Why UUID over SERIAL for the primary key?
The UUID data type provides a globally unique identifier that is not tied to a specific sequence
or server instance, making it ideal for distributed systems and ensuring uniqueness across different
environments. In contrast, SERIAL is an auto-incrementing integer that can lead to conflicts in
distributed setups and does not guarantee uniqueness across multiple databases. */

/* 2. Why uuidv7() specifically over uuidv4()? 
The uuidv7() function generates time-ordered UUIDs, which can improve performance when used as
primary keys in databases. Time-ordered UUIDs can reduce fragmentation and improve indexing
efficiency compared to random UUIDs generated by uuidv4(), which do not have any inherent order.
This makes uuidv7() a better choice for scenarios where the order of record creation is important,
such as in job queues. */

/* 3. Why JSONB over JSON?
The JSONB data type stores JSON data in a binary format, which allows for faster access and
querying compared to the plain JSON data type. JSONB supports indexing, which can significantly
improve performance when querying specific fields within the JSON data. Additionally, JSONB
automatically removes duplicate keys and does not preserve the order of object keys, which can lead
to more efficient storage. In contrast, JSON stores data as text and does not support indexing,
resulting in slower query performance when accessing specific fields. */

/* 4. Why TIMESTAMPTZ over TIMESTAMP?
The TIMESTAMPTZ data type includes time zone information, allowing for accurate representation of
timestamps across different time zones. This is particularly important in distributed systems or
applications that may be used globally, as it ensures that timestamps are consistent and can be
correctly interpreted regardless of the user's location. In contrast, the TIMESTAMP data type does
not include time zone information, which can lead to confusion and errors when dealing with timestamps
from different time zones. */

----- SAMPLE DATA -----

INSERT INTO
    music_jobs (payload)
VALUES (
    '{
        "filename": "wadani_le.mp3",
        "storage_path": "/music/uploads/wadani_le.mp3",
        "file_size": 5242880,
        "mime_type": "audio/mpeg",
        "title": "Wadani Le",
        "album": "Undeniable",
        "artist": "Supa G",
        "genre": "Punta Rock",
        "year": 2016,
        "duration": 167
    }'::JSONB
);

SELECT pg_sleep(1); -- Utilized to create a time gap between entries for testing purposes

INSERT INTO
    music_jobs (payload)
VALUES (
    '{
        "filename": "good_mawnin_belize.mp3",
        "storage_path": "/music/uploads/good_mawnin_belize.mp3",
        "file_size": 7340032,
        "mime_type": "audio/wav",
        "title": "Good Mawnin Belize",
        "album": "This is Belize",
        "artist": "Mr. Peters",
        "genre": "Tropical",
        "year": 2007,
        "duration": 195
    }'::JSONB
);

SELECT pg_sleep(1);

-- contains extra field "bitrate"
INSERT INTO
    music_jobs (payload)
VALUES (
    '{
        "filename": "born_deh.mp3",
        "storage_path": "/music/uploads/born_deh.mp3",
        "file_size": 10485760,
        "mime_type": "audio/mpeg",
        "title": "Born Deh",
        "album": "The Legend",
        "artist": "Lord Rhaburn",
        "genre": "Calypso",
        "year": 2009,
        "duration": 350,
        "bitrate": 320
    }'::JSONB
);

----- VERIFICATION QUERIES -----

/* 1. Show all jobs ordered by creation time
SELECT payload->>'title' AS title, created_at FROM music_jobs ORDER BY created_at;

       title        |          created_at           
--------------------+-------------------------------
 Wadani Le          | 2026-05-14 00:01:15.633682-06
 Good Mawnin Belize | 2026-05-14 00:01:16.637025-06
 Born Deh           | 2026-05-14 00:01:17.650626-06
(3 rows) */

/* 2. Extract just the filename and mime_type from each job 
SELECT payload->>'filename' AS filename, payload->>'mime_type' AS mime_type FROM music_jobs;

        filename        | mime_type  
------------------------+------------
 wadani_le.mp3          | audio/mpeg
 good_mawnin_belize.mp3 | audio/wav
 born_deh.mp3           | audio/mpeg
(3 rows) */

/* 3. Find only MP3 uploads
SELECT payload->>'filename' AS filename, payload->>'mime_type' AS mime_type
FROM music_jobs WHERE payload->>'mime_type' = 'audio/mpeg';

   filename    | mime_type  
---------------+------------
 wadani_le.mp3 | audio/mpeg
 born_deh.mp3  | audio/mpeg
(2 rows) */

/* 4. Find the job that has the extra field
SELECT payload->>'id' AS id, payload->>'filename' AS filename, payload->>'bitrate' AS bitrate
FROM music_jobs WHERE payload ? 'bitrate';

                  id                  |   filename   | bitrate 
--------------------------------------+--------------+---------
 019e2517-17d8-7a06-bb49-d8d0edcdc46c | born_deh.mp3 | 320
(1 row) */
